import XCTest
@testable import Hexagram

final class HexagramTests: XCTestCase {

    func testInit() throws {
        XCTAssertNil(Hexagram(number: .min))
        XCTAssertNil(Hexagram(number: -1))
        XCTAssertNil(Hexagram(number: 0))
        XCTAssertNil(Hexagram(number: 65))
        XCTAssertNil(Hexagram(number: .max))

        XCTAssertNil(Hexagram(lines: 64))
        XCTAssertNil(Hexagram(lines: .max))

        XCTAssertEqual(Hexagram(number: 1), Hexagram(lines: 63))
        XCTAssertEqual(Hexagram(number: 2), Hexagram(lines: 0))
        XCTAssertEqual(Hexagram(number: 3), Hexagram(lines: 34))
        XCTAssertEqual(Hexagram(number: 4), Hexagram(lines: 17))
        XCTAssertEqual(Hexagram(number: 5), Hexagram(lines: 58))
        XCTAssertEqual(Hexagram(number: 6), Hexagram(lines: 23))
        XCTAssertEqual(Hexagram(number: 7), Hexagram(lines: 16))
        XCTAssertEqual(Hexagram(number: 8), Hexagram(lines: 2))
        XCTAssertEqual(Hexagram(number: 9), Hexagram(lines: 59))
        XCTAssertEqual(Hexagram(number: 10), Hexagram(lines: 55))
        XCTAssertEqual(Hexagram(number: 11), Hexagram(lines: 56))
        XCTAssertEqual(Hexagram(number: 12), Hexagram(lines: 7))
        XCTAssertEqual(Hexagram(number: 13), Hexagram(lines: 47))
        XCTAssertEqual(Hexagram(number: 14), Hexagram(lines: 61))
        XCTAssertEqual(Hexagram(number: 15), Hexagram(lines: 8))
        XCTAssertEqual(Hexagram(number: 16), Hexagram(lines: 4))
        XCTAssertEqual(Hexagram(number: 17), Hexagram(lines: 38))
        XCTAssertEqual(Hexagram(number: 18), Hexagram(lines: 25))
        XCTAssertEqual(Hexagram(number: 19), Hexagram(lines: 48))
        XCTAssertEqual(Hexagram(number: 20), Hexagram(lines: 3))
        XCTAssertEqual(Hexagram(number: 21), Hexagram(lines: 37))
        XCTAssertEqual(Hexagram(number: 22), Hexagram(lines: 41))
        XCTAssertEqual(Hexagram(number: 23), Hexagram(lines: 1))
        XCTAssertEqual(Hexagram(number: 24), Hexagram(lines: 32))
        XCTAssertEqual(Hexagram(number: 25), Hexagram(lines: 39))
        XCTAssertEqual(Hexagram(number: 26), Hexagram(lines: 57))
        XCTAssertEqual(Hexagram(number: 27), Hexagram(lines: 33))
        XCTAssertEqual(Hexagram(number: 28), Hexagram(lines: 30))
        XCTAssertEqual(Hexagram(number: 29), Hexagram(lines: 18))
        XCTAssertEqual(Hexagram(number: 30), Hexagram(lines: 45))
        XCTAssertEqual(Hexagram(number: 31), Hexagram(lines: 14))
        XCTAssertEqual(Hexagram(number: 32), Hexagram(lines: 28))
        XCTAssertEqual(Hexagram(number: 33), Hexagram(lines: 15))
        XCTAssertEqual(Hexagram(number: 34), Hexagram(lines: 60))
        XCTAssertEqual(Hexagram(number: 35), Hexagram(lines: 5))
        XCTAssertEqual(Hexagram(number: 36), Hexagram(lines: 40))
        XCTAssertEqual(Hexagram(number: 37), Hexagram(lines: 43))
        XCTAssertEqual(Hexagram(number: 38), Hexagram(lines: 53))
        XCTAssertEqual(Hexagram(number: 39), Hexagram(lines: 10))
        XCTAssertEqual(Hexagram(number: 40), Hexagram(lines: 20))
        XCTAssertEqual(Hexagram(number: 41), Hexagram(lines: 49))
        XCTAssertEqual(Hexagram(number: 42), Hexagram(lines: 35))
        XCTAssertEqual(Hexagram(number: 43), Hexagram(lines: 62))
        XCTAssertEqual(Hexagram(number: 44), Hexagram(lines: 31))
        XCTAssertEqual(Hexagram(number: 45), Hexagram(lines: 6))
        XCTAssertEqual(Hexagram(number: 46), Hexagram(lines: 24))
        XCTAssertEqual(Hexagram(number: 47), Hexagram(lines: 22))
        XCTAssertEqual(Hexagram(number: 48), Hexagram(lines: 26))
        XCTAssertEqual(Hexagram(number: 49), Hexagram(lines: 46))
        XCTAssertEqual(Hexagram(number: 50), Hexagram(lines: 29))
        XCTAssertEqual(Hexagram(number: 51), Hexagram(lines: 36))
        XCTAssertEqual(Hexagram(number: 52), Hexagram(lines: 9))
        XCTAssertEqual(Hexagram(number: 53), Hexagram(lines: 11))
        XCTAssertEqual(Hexagram(number: 54), Hexagram(lines: 52))
        XCTAssertEqual(Hexagram(number: 55), Hexagram(lines: 44))
        XCTAssertEqual(Hexagram(number: 56), Hexagram(lines: 13))
        XCTAssertEqual(Hexagram(number: 57), Hexagram(lines: 27))
        XCTAssertEqual(Hexagram(number: 58), Hexagram(lines: 54))
        XCTAssertEqual(Hexagram(number: 59), Hexagram(lines: 19))
        XCTAssertEqual(Hexagram(number: 60), Hexagram(lines: 50))
        XCTAssertEqual(Hexagram(number: 61), Hexagram(lines: 51))
        XCTAssertEqual(Hexagram(number: 62), Hexagram(lines: 12))
        XCTAssertEqual(Hexagram(number: 63), Hexagram(lines: 42))
        XCTAssertEqual(Hexagram(number: 64), Hexagram(lines: 21))
    }

    func testName() throws {
        XCTAssertEqual(Hexagram(number: 1)?.name, "The Creative Heaven")
        XCTAssertEqual(Hexagram(number: 2)?.name, "The Receptive Earth")
        XCTAssertEqual(Hexagram(number: 3)?.name, "Difficulty At The Beginning")
        XCTAssertEqual(Hexagram(number: 4)?.name, "Youthful Folly")
        XCTAssertEqual(Hexagram(number: 5)?.name, "Waiting")
        XCTAssertEqual(Hexagram(number: 6)?.name, "Conflict")
        XCTAssertEqual(Hexagram(number: 7)?.name, "The Army")
        XCTAssertEqual(Hexagram(number: 8)?.name, "Holding Together")
        XCTAssertEqual(Hexagram(number: 9)?.name, "Small Taming")
        XCTAssertEqual(Hexagram(number: 10)?.name, "Treading")
        XCTAssertEqual(Hexagram(number: 11)?.name, "Peace")
        XCTAssertEqual(Hexagram(number: 12)?.name, "Standstill")
        XCTAssertEqual(Hexagram(number: 13)?.name, "Fellowship")
        XCTAssertEqual(Hexagram(number: 14)?.name, "Great Possession")
        XCTAssertEqual(Hexagram(number: 15)?.name, "Modesty")
        XCTAssertEqual(Hexagram(number: 16)?.name, "Enthusiasm")
        XCTAssertEqual(Hexagram(number: 17)?.name, "Following")
        XCTAssertEqual(Hexagram(number: 18)?.name, "Work On The Decayed")
        XCTAssertEqual(Hexagram(number: 19)?.name, "Approach")
        XCTAssertEqual(Hexagram(number: 20)?.name, "Contemplation")
        XCTAssertEqual(Hexagram(number: 21)?.name, "Biting Through")
        XCTAssertEqual(Hexagram(number: 22)?.name, "Grace")
        XCTAssertEqual(Hexagram(number: 23)?.name, "Splitting Apart")
        XCTAssertEqual(Hexagram(number: 24)?.name, "Return")
        XCTAssertEqual(Hexagram(number: 25)?.name, "Innocence")
        XCTAssertEqual(Hexagram(number: 26)?.name, "Great Taming")
        XCTAssertEqual(Hexagram(number: 27)?.name, "Mouth Corners")
        XCTAssertEqual(Hexagram(number: 28)?.name, "Great Preponderance")
        XCTAssertEqual(Hexagram(number: 29)?.name, "The Abysmal Water")
        XCTAssertEqual(Hexagram(number: 30)?.name, "The Clinging Fire")
        XCTAssertEqual(Hexagram(number: 31)?.name, "Influence")
        XCTAssertEqual(Hexagram(number: 32)?.name, "Duration")
        XCTAssertEqual(Hexagram(number: 33)?.name, "Retreat")
        XCTAssertEqual(Hexagram(number: 34)?.name, "Great Power")
        XCTAssertEqual(Hexagram(number: 35)?.name, "Progress")
        XCTAssertEqual(Hexagram(number: 36)?.name, "Darkening Of The Light")
        XCTAssertEqual(Hexagram(number: 37)?.name, "The Family")
        XCTAssertEqual(Hexagram(number: 38)?.name, "Opposition")
        XCTAssertEqual(Hexagram(number: 39)?.name, "Obstruction")
        XCTAssertEqual(Hexagram(number: 40)?.name, "Deliverance")
        XCTAssertEqual(Hexagram(number: 41)?.name, "Decrease")
        XCTAssertEqual(Hexagram(number: 42)?.name, "Increase")
        XCTAssertEqual(Hexagram(number: 43)?.name, "Breakthrough")
        XCTAssertEqual(Hexagram(number: 44)?.name, "Coming To Meet")
        XCTAssertEqual(Hexagram(number: 45)?.name, "Gathering Together")
        XCTAssertEqual(Hexagram(number: 46)?.name, "Pushing Upward")
        XCTAssertEqual(Hexagram(number: 47)?.name, "Oppression")
        XCTAssertEqual(Hexagram(number: 48)?.name, "The Well")
        XCTAssertEqual(Hexagram(number: 49)?.name, "Revolution")
        XCTAssertEqual(Hexagram(number: 50)?.name, "The Cauldron")
        XCTAssertEqual(Hexagram(number: 51)?.name, "The Arousing Thunder")
        XCTAssertEqual(Hexagram(number: 52)?.name, "The Keeping Still Mountain")
        XCTAssertEqual(Hexagram(number: 53)?.name, "Development")
        XCTAssertEqual(Hexagram(number: 54)?.name, "The Marrying Maiden")
        XCTAssertEqual(Hexagram(number: 55)?.name, "Abundance")
        XCTAssertEqual(Hexagram(number: 56)?.name, "The Wanderer")
        XCTAssertEqual(Hexagram(number: 57)?.name, "The Gentle Wind")
        XCTAssertEqual(Hexagram(number: 58)?.name, "The Joyous Lake")
        XCTAssertEqual(Hexagram(number: 59)?.name, "Dispersion")
        XCTAssertEqual(Hexagram(number: 60)?.name, "Limitation")
        XCTAssertEqual(Hexagram(number: 61)?.name, "Inner Truth")
        XCTAssertEqual(Hexagram(number: 62)?.name, "Small Preponderance")
        XCTAssertEqual(Hexagram(number: 63)?.name, "After Completion")
        XCTAssertEqual(Hexagram(number: 64)?.name, "Before Completion")
    }

    func testCharacter() throws {
        XCTAssertEqual(Hexagram(number: 1)?.character, "䷀")
        XCTAssertEqual(Hexagram(number: 2)?.character, "䷁")
        XCTAssertEqual(Hexagram(number: 3)?.character, "䷂")
        XCTAssertEqual(Hexagram(number: 4)?.character, "䷃")
        XCTAssertEqual(Hexagram(number: 5)?.character, "䷄")
        XCTAssertEqual(Hexagram(number: 6)?.character, "䷅")
        XCTAssertEqual(Hexagram(number: 7)?.character, "䷆")
        XCTAssertEqual(Hexagram(number: 8)?.character, "䷇")
        XCTAssertEqual(Hexagram(number: 9)?.character, "䷈")
        XCTAssertEqual(Hexagram(number: 10)?.character, "䷉")
        XCTAssertEqual(Hexagram(number: 11)?.character, "䷊")
        XCTAssertEqual(Hexagram(number: 12)?.character, "䷋")
        XCTAssertEqual(Hexagram(number: 13)?.character, "䷌")
        XCTAssertEqual(Hexagram(number: 14)?.character, "䷍")
        XCTAssertEqual(Hexagram(number: 15)?.character, "䷎")
        XCTAssertEqual(Hexagram(number: 16)?.character, "䷏")
        XCTAssertEqual(Hexagram(number: 17)?.character, "䷐")
        XCTAssertEqual(Hexagram(number: 18)?.character, "䷑")
        XCTAssertEqual(Hexagram(number: 19)?.character, "䷒")
        XCTAssertEqual(Hexagram(number: 20)?.character, "䷓")
        XCTAssertEqual(Hexagram(number: 21)?.character, "䷔")
        XCTAssertEqual(Hexagram(number: 22)?.character, "䷕")
        XCTAssertEqual(Hexagram(number: 23)?.character, "䷖")
        XCTAssertEqual(Hexagram(number: 24)?.character, "䷗")
        XCTAssertEqual(Hexagram(number: 25)?.character, "䷘")
        XCTAssertEqual(Hexagram(number: 26)?.character, "䷙")
        XCTAssertEqual(Hexagram(number: 27)?.character, "䷚")
        XCTAssertEqual(Hexagram(number: 28)?.character, "䷛")
        XCTAssertEqual(Hexagram(number: 29)?.character, "䷜")
        XCTAssertEqual(Hexagram(number: 30)?.character, "䷝")
        XCTAssertEqual(Hexagram(number: 31)?.character, "䷞")
        XCTAssertEqual(Hexagram(number: 32)?.character, "䷟")
        XCTAssertEqual(Hexagram(number: 33)?.character, "䷠")
        XCTAssertEqual(Hexagram(number: 34)?.character, "䷡")
        XCTAssertEqual(Hexagram(number: 35)?.character, "䷢")
        XCTAssertEqual(Hexagram(number: 36)?.character, "䷣")
        XCTAssertEqual(Hexagram(number: 37)?.character, "䷤")
        XCTAssertEqual(Hexagram(number: 38)?.character, "䷥")
        XCTAssertEqual(Hexagram(number: 39)?.character, "䷦")
        XCTAssertEqual(Hexagram(number: 40)?.character, "䷧")
        XCTAssertEqual(Hexagram(number: 41)?.character, "䷨")
        XCTAssertEqual(Hexagram(number: 42)?.character, "䷩")
        XCTAssertEqual(Hexagram(number: 43)?.character, "䷪")
        XCTAssertEqual(Hexagram(number: 44)?.character, "䷫")
        XCTAssertEqual(Hexagram(number: 45)?.character, "䷬")
        XCTAssertEqual(Hexagram(number: 46)?.character, "䷭")
        XCTAssertEqual(Hexagram(number: 47)?.character, "䷮")
        XCTAssertEqual(Hexagram(number: 48)?.character, "䷯")
        XCTAssertEqual(Hexagram(number: 49)?.character, "䷰")
        XCTAssertEqual(Hexagram(number: 50)?.character, "䷱")
        XCTAssertEqual(Hexagram(number: 51)?.character, "䷲")
        XCTAssertEqual(Hexagram(number: 52)?.character, "䷳")
        XCTAssertEqual(Hexagram(number: 53)?.character, "䷴")
        XCTAssertEqual(Hexagram(number: 54)?.character, "䷵")
        XCTAssertEqual(Hexagram(number: 55)?.character, "䷶")
        XCTAssertEqual(Hexagram(number: 56)?.character, "䷷")
        XCTAssertEqual(Hexagram(number: 57)?.character, "䷸")
        XCTAssertEqual(Hexagram(number: 58)?.character, "䷹")
        XCTAssertEqual(Hexagram(number: 59)?.character, "䷺")
        XCTAssertEqual(Hexagram(number: 60)?.character, "䷻")
        XCTAssertEqual(Hexagram(number: 61)?.character, "䷼")
        XCTAssertEqual(Hexagram(number: 62)?.character, "䷽")
        XCTAssertEqual(Hexagram(number: 63)?.character, "䷾")
        XCTAssertEqual(Hexagram(number: 64)?.character, "䷿")
    }

    func testUpperTrigram() throws {
        XCTAssertEqual(Hexagram(number: 1)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 2)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 3)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 4)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 5)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 6)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 7)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 8)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 9)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 10)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 11)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 12)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 13)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 14)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 15)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 16)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 17)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 18)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 19)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 20)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 21)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 22)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 23)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 24)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 25)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 26)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 27)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 28)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 29)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 30)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 31)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 32)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 33)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 34)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 35)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 36)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 37)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 38)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 39)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 40)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 41)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 42)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 43)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 44)?.upperTrigram, 7)
        XCTAssertEqual(Hexagram(number: 45)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 46)?.upperTrigram, 0)
        XCTAssertEqual(Hexagram(number: 47)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 48)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 49)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 50)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 51)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 52)?.upperTrigram, 1)
        XCTAssertEqual(Hexagram(number: 53)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 54)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 55)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 56)?.upperTrigram, 5)
        XCTAssertEqual(Hexagram(number: 57)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 58)?.upperTrigram, 6)
        XCTAssertEqual(Hexagram(number: 59)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 60)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 61)?.upperTrigram, 3)
        XCTAssertEqual(Hexagram(number: 62)?.upperTrigram, 4)
        XCTAssertEqual(Hexagram(number: 63)?.upperTrigram, 2)
        XCTAssertEqual(Hexagram(number: 64)?.upperTrigram, 5)
    }

    func testLowerTrigram() throws {
        XCTAssertEqual(Hexagram(number: 1)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 2)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 3)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 4)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 5)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 6)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 7)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 8)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 9)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 10)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 11)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 12)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 13)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 14)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 15)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 16)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 17)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 18)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 19)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 20)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 21)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 22)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 23)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 24)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 25)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 26)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 27)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 28)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 29)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 30)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 31)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 32)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 33)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 34)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 35)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 36)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 37)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 38)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 39)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 40)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 41)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 42)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 43)?.lowerTrigram, 7)
        XCTAssertEqual(Hexagram(number: 44)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 45)?.lowerTrigram, 0)
        XCTAssertEqual(Hexagram(number: 46)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 47)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 48)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 49)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 50)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 51)?.lowerTrigram, 4)
        XCTAssertEqual(Hexagram(number: 52)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 53)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 54)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 55)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 56)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 57)?.lowerTrigram, 3)
        XCTAssertEqual(Hexagram(number: 58)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 59)?.lowerTrigram, 2)
        XCTAssertEqual(Hexagram(number: 60)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 61)?.lowerTrigram, 6)
        XCTAssertEqual(Hexagram(number: 62)?.lowerTrigram, 1)
        XCTAssertEqual(Hexagram(number: 63)?.lowerTrigram, 5)
        XCTAssertEqual(Hexagram(number: 64)?.lowerTrigram, 2)
    }

    func testUpperTrigramName() throws {
        XCTAssertEqual(Hexagram(number: 1)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 2)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 3)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 4)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 5)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 6)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 7)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 8)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 9)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 10)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 11)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 12)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 13)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 14)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 15)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 16)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 17)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 18)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 19)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 20)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 21)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 22)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 23)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 24)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 25)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 26)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 27)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 28)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 29)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 30)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 31)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 32)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 33)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 34)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 35)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 36)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 37)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 38)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 39)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 40)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 41)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 42)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 43)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 44)?.upperTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 45)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 46)?.upperTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 47)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 48)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 49)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 50)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 51)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 52)?.upperTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 53)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 54)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 55)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 56)?.upperTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 57)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 58)?.upperTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 59)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 60)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 61)?.upperTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 62)?.upperTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 63)?.upperTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 64)?.upperTrigramName, "Fire")
    }

    func testLowerTrigramName() throws {
        XCTAssertEqual(Hexagram(number: 1)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 2)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 3)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 4)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 5)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 6)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 7)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 8)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 9)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 10)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 11)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 12)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 13)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 14)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 15)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 16)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 17)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 18)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 19)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 20)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 21)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 22)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 23)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 24)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 25)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 26)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 27)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 28)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 29)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 30)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 31)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 32)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 33)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 34)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 35)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 36)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 37)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 38)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 39)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 40)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 41)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 42)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 43)?.lowerTrigramName, "Heaven")
        XCTAssertEqual(Hexagram(number: 44)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 45)?.lowerTrigramName, "Earth")
        XCTAssertEqual(Hexagram(number: 46)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 47)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 48)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 49)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 50)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 51)?.lowerTrigramName, "Thunder")
        XCTAssertEqual(Hexagram(number: 52)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 53)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 54)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 55)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 56)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 57)?.lowerTrigramName, "Wind")
        XCTAssertEqual(Hexagram(number: 58)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 59)?.lowerTrigramName, "Water")
        XCTAssertEqual(Hexagram(number: 60)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 61)?.lowerTrigramName, "Lake")
        XCTAssertEqual(Hexagram(number: 62)?.lowerTrigramName, "Mountain")
        XCTAssertEqual(Hexagram(number: 63)?.lowerTrigramName, "Fire")
        XCTAssertEqual(Hexagram(number: 64)?.lowerTrigramName, "Water")
    }

    func testUpperTrigramCharacter() throws {
        XCTAssertEqual(Hexagram(number: 1)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 2)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 3)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 4)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 5)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 6)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 7)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 8)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 9)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 10)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 11)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 12)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 13)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 14)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 15)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 16)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 17)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 18)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 19)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 20)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 21)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 22)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 23)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 24)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 25)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 26)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 27)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 28)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 29)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 30)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 31)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 32)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 33)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 34)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 35)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 36)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 37)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 38)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 39)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 40)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 41)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 42)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 43)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 44)?.upperTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 45)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 46)?.upperTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 47)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 48)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 49)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 50)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 51)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 52)?.upperTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 53)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 54)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 55)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 56)?.upperTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 57)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 58)?.upperTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 59)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 60)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 61)?.upperTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 62)?.upperTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 63)?.upperTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 64)?.upperTrigramCharacter, "☲")
    }

    func testLowerTrigramCharacter() throws {
        XCTAssertEqual(Hexagram(number: 1)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 2)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 3)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 4)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 5)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 6)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 7)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 8)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 9)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 10)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 11)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 12)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 13)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 14)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 15)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 16)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 17)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 18)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 19)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 20)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 21)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 22)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 23)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 24)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 25)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 26)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 27)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 28)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 29)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 30)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 31)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 32)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 33)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 34)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 35)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 36)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 37)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 38)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 39)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 40)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 41)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 42)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 43)?.lowerTrigramCharacter, "☰")
        XCTAssertEqual(Hexagram(number: 44)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 45)?.lowerTrigramCharacter, "☷")
        XCTAssertEqual(Hexagram(number: 46)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 47)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 48)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 49)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 50)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 51)?.lowerTrigramCharacter, "☳")
        XCTAssertEqual(Hexagram(number: 52)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 53)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 54)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 55)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 56)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 57)?.lowerTrigramCharacter, "☴")
        XCTAssertEqual(Hexagram(number: 58)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 59)?.lowerTrigramCharacter, "☵")
        XCTAssertEqual(Hexagram(number: 60)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 61)?.lowerTrigramCharacter, "☱")
        XCTAssertEqual(Hexagram(number: 62)?.lowerTrigramCharacter, "☶")
        XCTAssertEqual(Hexagram(number: 63)?.lowerTrigramCharacter, "☲")
        XCTAssertEqual(Hexagram(number: 64)?.lowerTrigramCharacter, "☵")
    }
    
}
